# Generated by Django 3.0 on 2020-05-20 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Gender', multiselectfield.db.fields.MultiSelectField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=17)),
                ('Age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('register', multiselectfield.db.fields.MultiSelectField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=14)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
