# Generated by Django 3.0 on 2020-05-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
