# Generated by Django 3.0 on 2020-05-20 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosmng', '0003_auto_20200520_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(blank=True, max_length=300, null=True)),
                ('disease', models.CharField(blank=True, max_length=300, null=True)),
                ('invoice', models.ImageField(default='Not present', upload_to='images')),
                ('payment', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Gender', multiselectfield.db.fields.MultiSelectField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=17)),
                ('Age', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('date_avail', models.DateField(auto_now_add=True, null=True)),
                ('time_avail', models.TimeField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Cardiology', 'Cardiology'), ('OPD', 'OPD'), ('Dental', 'Dental')], max_length=30, null=True)),
                ('attendance', models.CharField(blank=True, max_length=30, null=True)),
                ('salary', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('doc_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosmng.Doctor')),
                ('pat_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hosmng.Patient')),
            ],
        ),
    ]
