# Generated by Django 3.0 on 2020-05-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0004_appointment_doctor_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_avail',
            field=models.DateField(blank=True, null=True),
        ),
    ]
