# Generated by Django 3.0 on 2020-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0007_remove_patient_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=20, null=True)),
            ],
        ),
    ]
