# Generated by Django 3.0 on 2020-05-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0009_auto_20200521_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
