# Generated by Django 3.0 on 2020-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0011_auto_20200521_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='sr_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
