# Generated by Django 3.0 on 2020-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0014_auto_20200521_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
    ]
