# Generated by Django 3.0 on 2020-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0015_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
