# Generated by Django 3.0 on 2020-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0017_doctor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='total_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
