# Generated by Django 3.0 on 2020-05-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0019_auto_20200522_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='med_reps',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
