# Generated by Django 3.0 on 2020-05-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosmng', '0020_patient_med_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='case_paper',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
